### ISSUE TITLE
CSV mode, usernames are without quotes

### ISSUE THREAD

**Issue by crayxt** [Kosat/telegram-messages-dump#19]
Hi,
First of all, thanks for such an useful utility!

Now, when I tried to export some chat history, I found that one username has ',' in it, and usernames field is not surrounded by quotes. Can you please change CSV writer to put quotes around username field?

Thanks,

**Comment by Kosat** [comment]
Hi @crayxt,

Good point. Try it again with the new commit 01efdd0. It should be working as you described. 

Thanks

**Comment by crayxt** [comment]
@Kosat I think, we need to quote all usernames.

**Comment by Kosat** [comment]
Nope, according to the [rfc4180](https://www.ietf.org/rfc/rfc4180.txt) we can use quotes only when needed. If a field doesn't contain 'problematic' characters then the quotes can be omitted.

Check this part of RFC. Note the part (6), where they use quotes in row 1: "aa ... ccc" and then in row 2: zz ... xxx they don't use quotes because there are no special characters in fields there. 

```CSV
   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx
```

Ignore the 01efdd0. It should be like in 5f155fd.

**Comment by crayxt** [comment]
@Kosat Ok, but I am only able to check out release, cannot build from sources atm. Hopefully, that will work

**Comment by Kosat** [comment]
You can now check [v0.3.4](https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.4) release.
